### ISSUE TITLE
Refactor Code

### ISSUE THREAD

**Issue by hfgem** [hfgem/BlechCodes#67]
This code is a mess! Time for a refactor to create a clean pipeline of data analysis.

**Part 1: Params File**
Since some parameters are kept constant across analyses of a dataset, create a params file that is copied from a template in the GitHub BlechCodes repository into the dataset folder and updated by the user prior to running analyses.
- [x] Design a params file that captures parameters used across different calculations in the pipeline

**Part 2: Major Refactor**
- [x] Create a master script that runs analysis
- [ ] Convert existing code into a pipeline that passes params and data information to the correct pipeline step
- [x] Have a means of storing the step the pipeline is at in analysis, and starting from that step if the master script is called to analyze the dataset
